# Generated by Django 4.2.16 on 2024-12-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_water_requi_dummy_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_requi_dummy',
            name='daily_wr_liters',
            field=models.FloatField(null=True),
        ),
    ]
