# Generated by Django 4.2.16 on 2024-12-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alert_irrig_sched_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrig_sched',
            name='crop_name',
        ),
        migrations.RemoveField(
            model_name='irrig_sched',
            name='scheduled_irrigation_liters',
        ),
        migrations.AddField(
            model_name='irrig_sched',
            name='avai_water',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='irrig_sched',
            name='total_water_requi_day',
            field=models.FloatField(null=True),
        ),
    ]
