# Generated by Django 4.2.16 on 2024-12-03 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_irrig_sched_crop_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('soil_moisture', models.FloatField()),
                ('temperature', models.FloatField()),
                ('npk_values', models.TextField()),
            ],
        ),
    ]
