# Generated by Django 4.2.16 on 2024-12-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_rainfalldata_predicted_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermoutput',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rainfalldata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='season',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='shorttermoutput',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='temperaturedata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='water_level_prophetreg',
            name='date',
            field=models.DateField(),
        ),
    ]
