# Generated by Django 4.2.16 on 2024-12-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_dam_data_longtermoutput_silt'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermoutput',
            name='req_mm',
            field=models.FloatField(null=True),
        ),
    ]
