# Generated by Django 4.2.16 on 2024-12-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_longtermoutput_req_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmodeloutputs',
            name='evaporation_loss',
            field=models.FloatField(null=True),
        ),
    ]
