# Generated by Django 4.2.16 on 2024-12-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_predmodeloutputs_evaporation_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_requi',
            name='daily_domestic_requi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='water_requi',
            name='daily_idustrial_requi',
            field=models.FloatField(null=True),
        ),
    ]
