# Generated by Django 4.2.16 on 2024-12-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_water_requi_daily_domestic_requi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermoutput',
            name='actual_avia_water_mm',
            field=models.FloatField(null=True),
        ),
    ]
