# Generated by Django 4.2.16 on 2024-12-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_longtermoutput_actual_avia_water_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dam_data',
            name='damn_area',
            field=models.FloatField(null=True),
        ),
    ]
