# Generated by Django 4.2.16 on 2024-12-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_longtermoutput_req_litres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermoutput',
            name='req_litres',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='longtermoutput',
            name='water_difference',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='predmodeloutputs',
            name='water_level_xgb',
            field=models.FloatField(null=True),
        ),
    ]
